### PR TITLE
Added DevBox to closed source apps in readme.

### PR DESCRIPTION
**Pull request by gdotdesign**
This is the link to the project: [TITLE](URL)

- [x] **I have read the [contributing guidelines](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] Add entries to the bottom of the correct category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [ ] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The template provides enough information about how to get started and what's included.
- [ ] The template is pretty different from the existing templates.

### Apps

- [x] The app is original and not too simple.
- [x] The README is in English.
- [x] The app makes a reasonable effort to be fast, lightweight and secure.
- [x] If the app closed source, evidence of it being built with Tauri is included.

### Additional Context
Evidence is in the bottom of the page:
image

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
Hey! Thanks for your submission, our process for closed source apps isn't fleshed out yet (considering your the second developer submitting one), but I hope you understand a simple claim from the website isn't enough. 

In the past we had the developer send us a debug build of his app privately. I would also be fine with a screen recording of you launching the app in development mode. 

Feel free to reach out to me via email if you want to send me the proof privately.

**Comment by gdotdesign** [comment]
Thanks! I'll upload a screen recording tomorrow with the debug build.

**Comment by gdotdesign** [comment]
Here is the screen recording:
https://user-images.githubusercontent.com/302692/175525153-42b27c37-a14c-4f78-9d39-56dfd2b5284a.mp4

**Comment by JonasKruckenberg** [comment]
Somehow your video got corrupted it seems :/
Screen Shot 2022-06-28 at 15 47 30

**Comment by gdotdesign** [comment]
Yeah, it shows that for me the first time, but after I refresh with Ctrl+F5 it loads. If that doesn't work, I'll upload it somewhere else.

**Comment by JonasKruckenberg** [comment]
> Yeah, it shows that for me the first time, but after I refresh with Ctrl+F5 it loads. If that doesn't work, I'll upload it somewhere else.

Oh yeah thanks! Worked 👍🏻 

I call that enough evidence 😉 thanks!

**Review by JonasKruckenberg — APPROVED** [review]

**Pull request merged**
