### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dgu87**
- [x] **I have read the [contributing guidelines](contributing.md).**

- [x] Title as described.
- [x] Added to the right category.
- [x] Added to the end of a list.
- [x] The description of your item is a sentence with less than 24 words.
- [x] No links and parentheses in description. 
- [x] The description starts with a capital and ends with a full stop/period.
- [x] The description doesn't start with `A` or `An`.
- [x] No unnecessary words already provided in the context (e.g. `for Tauri`, `a Tauri plugin`).
- [x] Uses proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [x] When mentioning tools, omits versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`.
- [x] When mentioning package names, uses quotes whenever possible.

### Plugins/Tools

- [ ] The plugin/tool is working with **Tauri 1.x and onward**.
- [ ] The project is Open Source.
- [ ] The repo should be at least 30 days old.
- [ ] The documentation is in English.
- [ ] The project is active and maintained (inactive projects for longer 6 months will be removed without further notice).
- [ ] The project accepts contributions.
- [ ] Not a commercial product.

### Starter Templates

- [ ] The starter template is working with **Tauri 1.x and onward**.
- [ ] The documentation is in English.
- [ ] The starter template most provide enough instructions / documentation about how to start up and what's is included.
- [ ] The repo should be at least 30 days old.
- [ ] Should be differentiable from the existing starter templates.

### Apps

- [ ] The project is Open Source.
- [ ] The readme is in English.
- [x] The app is original and not too simple.

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
Thanks for your submission!
Please note that we're quite a bit stricter with closed source apps than open source ones, so be patient while we review your request.

**Comment by dgu87** [comment]
Thanks & no worries. Just let me know if you need any additional information / proof of using tauri / etc.

**Comment by JonasKruckenberg** [comment]
> Thanks & no worries. Just let me know if you need any additional information / proof of using tauri / etc.

Actually that'd be great, you app looks awesome otherwise! I don't know how best to "proof" that you're using tauri, but maybe run `tauri info` or take a screenshot that demonstrates your app using tauri. 
You can also send that to my email (iterpre@protonmail.com) if you're not comfortable sharing that public 👍🏻

**Comment by dgu87** [comment]
Thanks for your feedback. Really appreciate it :) I just sent you an email with a PoT-Screenshot.

I think I'll publish the code here on GitHub as soon as I find the time to tidy it up a bit.

**Comment by JonasKruckenberg** [comment]
Got it and lgtm 👍🏻

Edit: If you publish your project as Open Source just shoot us another PR to sort it into the correct category!

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by dgu87** [comment]
Thx. Will do!

**Pull request merged**
