### PR TITLE
Added jasnoo

### PR DESCRIPTION
**Pull request by mzzovko**
This is the link to the project: [jasnoo](https://jasnoo.com)

- [x] **I have read the [contributing guidelines](https://github.com/tauri-apps/awesome-tauri/blob/dev/.github/contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] If the project is closed source add the `![closed source]` badge after the `(link)` but before the `-`.
- [x] If the project/article is non-free or paywalled add the `![paid]` badge after the `(link)` but before the `-`.
- [x] Add entries alphabetically to the most appropriate category.
- [x No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Additional Context
Video of a debug build running on my computer with Tauri.
[Screencast from 08-07-2024 07:05:20 PM.webm](https://github.com/user-attachments/assets/13248bc4-f388-492a-a091-d376a10c7aca)

### CODE REVIEW

**Comment by FabianLars** [comment]
Hey 👋 Thanks for opening a PR! Can you provide some kind of proof that your app was created with tauri? (For example a screenshot of your app with `tauri dev` running)

**Comment by mzzovko** [comment]
> Hey 👋 Thanks for opening a PR! Can you provide some kind of proof that your app was created with tauri? (For example a screenshot of your app with `tauri dev` running)

Hi @FabianLars , sorry it seems my previous video didn't preview correctly here. ~~Here is another:~~

Edit: Sorry for triple edit, but something is wrong with uploading .mp4 files here. It doesn't manage to play them properly unless you are scrubbing them manually. Can you please use the link I left in initial post. And here are additional screenshots, which hopefully work as they should.

Screenshot from 2024-08-08 03-17-13
Screenshot from 2024-08-08 03-16-51
Screenshot from 2024-08-08 03-15-32

**Comment by FabianLars** [comment]
oh my, i totally missed the video in the initial post, sorry!!

**Review by FabianLars — APPROVED** [review]
thanks!!

**Pull request merged**
