### PR TITLE
Add Calciumdibromid App

### PR DESCRIPTION
**Pull request by 6543**
- [ ] **I have read the [contributing guidelines](contributing.md).** - **no THEY do NOT exist**
### Main

- [x] Title as described.
- [x] Added to the right category.
- [x] Added to the end of a list.
- [x] The description of your item is a sentence with less than 24 words.
- [x] No links and parentheses in description. 
- [x] The description starts with a capital and ends with a full stop/period.
- [x] The description doesn't start with `A` or `An`.
- [x] No unnecessary words already provided in the context (e.g. `for Tauri`, `a Tauri plugin`).
- [x] Uses proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [x] When mentioning tools, omits versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`.
- [x] When mentioning package names, uses quotes whenever possible.

### Plugins/Tools

- [ ] The plugin/tool is working with **Tauri 1.x and onward**.
- [ ] The project is Open Source.
- [ ] The repo should be at least 30 days old.
- [ ] The documentation is in English.
- [ ] The project is active and maintained (inactive projects for longer 6 months will be removed without further notice).
- [ ] The project accepts contributions.
- [ ] Not a commercial product.

### Starter Templates

- [ ] The starter template is working with **Tauri 1.x and onward**.
- [ ] The documentation is in English.
- [ ] The starter template most provide enough instructions / documentation about how to start up and what's is included.
- [ ] The repo should be at least 30 days old.
- [ ] Should be differentiable from the existing starter templates.

### Apps

- [x] The project is Open Source.
- [x] The readme is in English.
- [x] The app is original and not too simple.

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
Please fill out the PR template.
Also don't sort the list, the order is first come-first serve as you can read in the [Contribution Guidelines](https://github.com/tauri-apps/awesome-tauri/blob/dev/.github/contributing.md):

> Always add your items to the end of a list. To be fair, the order is first-come-first-serve.

**Comment by 6543** [comment]
rebasing ...

**Comment by 6543** [comment]
@JonasKruckenberg updated :rocket:

PS: thanks for ping us in the first place :)

**Comment by JonasKruckenberg** [comment]
> * [ ]  **I have read the [contributing guidelines](contributing.md).** - **no THEY do NOT exist**

They do if you let github generate the PR from the template 😄 but all good 👍🏻

**Review by JonasKruckenberg — APPROVED** [review]

**Pull request merged**
