### PR TITLE
Improve grammar and word choice

### PR DESCRIPTION
**Pull request by zakpatterson**
Bullet points refer to the submitter / submission as well as just the app.

- [x] **I have read the [contributing guidelines](contributing.md).**

Just suggesting a couple changes to guidelines.

### CODE REVIEW

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
Lgtm, but is it correct to say "Apps give you" when talking about a category? Wouldn't it still be "Apps gives" bc it's the singular category?

**Comment by zakpatterson** [comment]
> Alternatively, it could be referring to the **Apps** section of this document, in which case perhaps it should be "The Apps section gives the opportunity..."

Yeah sorry, confusing wording I meant the **Apps** section. If you could update the PR with that last phrase It'd be swell

**Comment by JonasKruckenberg** [comment]
Shit sorry, I tapped the wrong button. 😅 Didn't mean to edit your reply, how unprofessional if me

**Comment by probablykasper** [comment]
Let's change it to "The apps section" to make it clearer

**Comment by JonasKruckenberg** [comment]
> Let's change it to "The apps section" to make it clearer

Yeah that was what @zakpatterson suggested, it doesn't say that anymore now obviously 🤦‍♂️ but I agree nonetheless

**Comment by JonasKruckenberg** [comment]
Awesome, and sorry again @zakpatterson 😅

**Comment by zakpatterson** [comment]
Sure no problem!

**Pull request merged**
