### PR TITLE
Add Spacedrive

### PR DESCRIPTION
**Pull request by DoomHammer**
This is the link to the project: [TITLE](URL)

- [X] **I have read the [contributing guidelines](contributing.md).**
- [X] Use the following format: `[Title](link) - Description.`
- [X] Add entries to the bottom of the correct category.
- [X] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [X] Description is under 24 words.
- [X] Description has no links or parenthesis.
- [X] Use `backticks` when mentioning package names.
- [X] Double-check spelling and grammar.
- [X] No trailing whitespace is added to the end of any file.
- [X] One suggestion per pull request.
- [X] I understand that my entry will be removed if it violates the guidelines.
- [ ] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The template provides enough information about how to get started and what's included.
- [ ] The template is pretty different from the existing templates.

### Apps

- [X] The app is original and not too simple.
- [X] The README is in English.
- [X] The app makes a reasonable effort to be fast, lightweight and secure.
- [ ] If the app closed source, evidence of it being built with Tauri is included.

### CODE REVIEW

**Review by JonasKruckenberg — CHANGES_REQUESTED** [review]
You need to sign your commits so we can merge this PR!

**Comment by JonasKruckenberg** [comment]
No wait, turns out GH mobile is just bad. Sorry 😅

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
But if you could do quick rebase we can merge this!

**Comment by DoomHammer** [comment]
Done!

**Comment by JonasKruckenberg** [comment]
Awesome! But now you actually *do* need to sign that commit 😂 sorry for the trouble!

**Comment by JonasKruckenberg** [comment]
hey @DoomHammer can you quickly sign these commits so we can get your app listed?

**Comment by DoomHammer** [comment]
Sorry, I might've missed something

**Pull request merged**
