### PR TITLE
Add Stable Diffusion Buddy open source Tauri app

### PR DESCRIPTION
**Pull request by breadthe**
This is the link to the project: [Stable Diffusion Buddy](https://github.com/breadthe/sd-buddy)

- [x] **I have read the [contributing guidelines](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] Add entries to the bottom of the correct category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Apps

- [x] The app is original and not too simple.
- [x] The README is in English.
- [x] The app makes a reasonable effort to be fast, lightweight and secure.
- [x] If the app closed source, evidence of it being built with Tauri is included.

### CODE REVIEW

**Review by JonasKruckenberg — CHANGES_REQUESTED** [review]
Only one thing of note: You should change the app icon, the default tauri icon does not work (trademark and stuff)

**Comment by breadthe** [comment]
Got it. Ok to leave this PR open until I change the icon? It may take a while until I find inspiration :)

**Comment by JonasKruckenberg** [comment]
> Got it. Ok to leave this PR open until I change the icon? It may take a while until I find inspiration :)

Hot tip: You got a nice tool for that with your app ;) [See this icon](https://discord.com/channels/616186924390023171/618328921330417692/1018208578550636655) I made using SD and a bit of touching up in Figma 😁

Edit: And yea, just tell me here when you have an icon and we can merge the PR!

**Comment by breadthe** [comment]
Awesome! That's a doh moment for me!

**Comment by breadthe** [comment]
Square30x30Logo We now have a new icon! And yes, I used the app to generate inspiration 😄

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
Awesome! Thank's for being part of the community!

**Pull request merged**
