### PR TITLE
[Jexpe] Cross-platform, open source SSH and SFTP client.

### PR DESCRIPTION
**Pull request by raccoman**
This is the link to the project: [Jexpe](https://github.com/jexpe-apps/jexpe)

- [x] **I have read the [contributing guidelines](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] Add entries to the bottom of the correct category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Apps

- [x] The app is original and not too simple.
- [x] The README is in English.
- [x] The app makes a reasonable effort to be fast, lightweight and secure.
- [x] If the app closed source, evidence of it being built with Tauri is included.

### CODE REVIEW

**Review by JonasKruckenberg — CHANGES_REQUESTED** [review]
Please configure the allowlist to only enable features your app is actually using https://github.com/jexpe-apps/jexpe/blob/d2f718a99dfdf0331a2e42d7ed7b7563d053dbf2/src-tauri/jexpe/tauri.conf.json#L14

And may consider changing this to a strict CSP https://github.com/jexpe-apps/jexpe/blob/d2f718a99dfdf0331a2e42d7ed7b7563d053dbf2/src-tauri/jexpe/tauri.conf.json#L50

**Comment by raccoman** [comment]
> Please configure the allowlist to only enable features your app is actually using https://github.com/jexpe-apps/jexpe/blob/d2f718a99dfdf0331a2e42d7ed7b7563d053dbf2/src-tauri/jexpe/tauri.conf.json#L14
> 
> And may consider changing this to a strict CSP https://github.com/jexpe-apps/jexpe/blob/d2f718a99dfdf0331a2e42d7ed7b7563d053dbf2/src-tauri/jexpe/tauri.conf.json#L50

Thank you for reminding me, I just fixed it

**Comment by JonasKruckenberg** [comment]
Ideally you should limit the CSP directive to a subset of protocol since `img-src *;` will also allow mixed-origin content and stuff like `file://`and weirder protocols, but I'm not gonna be too pedantic about it ;)

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by raccoman** [comment]
> Ideally you should limit the CSP directive to a subset of protocol since `img-src *;` will also allow mixed-origin content and stuff like `file://`and weirder protocols, but I'm not gonna be too pedantic about it ;)

Oh thanks! I'm going to change it

**Pull request merged**
