### PR TITLE
Add an open source app based on tauri.

### PR DESCRIPTION
**Pull request by lolieatcat**
This is the link to the project: [Aries Wallet](https://github.com/aries-wallet/aries-wallet)

- [x] **I have read the [contributing guidelines](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] Add entries to the bottom of the correct category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Apps

- [x] The app is original and not too simple.
- [x] The README is in English.
- [x] The app makes a reasonable effort to be fast, lightweight and secure.
- [x] If the app closed source, evidence of it being built with Tauri is included.

### CODE REVIEW

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
Please rebase this so we can merge this PR!

**Comment by JonasKruckenberg** [comment]
Ping @molin0000 your PR is approved and everything, you just need to resolve this merge conflict and your app is listed!

**Comment by simonhyll** [comment]
@lolieatcat We have update the structure of the README, please update your commit to reflect this change.

**Comment by simonhyll** [comment]
Closing this PR as it hasn't had any activity in a long time.
@lolieatcat Feel free to open a new PR when you're ready!

**Pull request closed without merging**
