### PR TITLE
Condense repo link and project names

### PR DESCRIPTION
**Pull request by zakpatterson**
Just a suggestion, that if you move all the links to the bottom and condense the repo links and the app names, I think both the source and output will be more readable after hundreds (thousands?) of things get added to this page.

### CODE REVIEW

**Comment by probablykasper** [comment]
I'd prefer if the links are on the same line, so everything is in one place.

I think it might be even better if it's a list:

## Plugins
- [Tauri Plugin Positioner](https://github.com/JonasKruckenberg/tauri-plugin-positioner) - Helps positioning Tauri windows at known locations
- [Tauri Plugin Stronghold](https://github.com/tauri-apps/tauri-plugin-stronghold) - An official Tauri Plugin for using Stronghold
- [Tauri Plugin Authenticator](https://github.com/tauri-apps/tauri-plugin-authenticator) - An official Tauri plugin for using a yubikey in your Tauri App
- [Tauri Plugin Log](https://github.com/tauri-apps/tauri-plugin-log) - Configurable interfaces for capturing and storing logs
- [Tauri Plugin SQL](https://github.com/tauri-apps/tauri-plugin-sql) - A "classical" Tauri Plugin Interface to SQL databases through [sqlx](https://github.com/launchbadge/sqlx)

vs:

## Plugins
| Repo | Description |
|-|-|
| [Tauri Plugin Positioner](https://github.com/JonasKruckenberg/tauri-plugin-positioner) | Helps positioning Tauri windows at known locations |
| [Tauri Plugin Stronghold](https://github.com/tauri-apps/tauri-plugin-stronghold) | An official Tauri Plugin for using Stronghold |
| [Tauri Plugin Authenticator](https://github.com/tauri-apps/tauri-plugin-authenticator) | An official Tauri plugin for using a yubikey in your Tauri App |
| [Tauri Plugin Log](https://github.com/tauri-apps/tauri-plugin-log) | Configurable interfaces for capturing and storing logs |
| [Tauri Plugin SQL](https://github.com/tauri-apps/tauri-plugin-sql) | A "classical" Tauri Plugin Interface to SQL databases through [sqlx](https://github.com/launchbadge/sqlx) |

**Comment by lorenzolewis** [comment]
I think a table is much better (especially with the alternating rows)

Here's one I really like https://github.com/pawelborkar/awesome-repos

**Comment by probablykasper** [comment]
Not really a fan of tables for this because they take up more space, and you often end up with unideal line wrapping, and most of all they can get pretty bad on mobile

If you need 3+ columns, then an equivalent list does start to get ugly (though at that point you're guaranteed to get unideal wrapping and horizontal scrolling on mobile, so still tradeoffs to consider)

**Comment by amrbashir** [comment]
I agree, list > tables.

**Comment by JonasKruckenberg** [comment]
> I agree, list > tables.

Indeed, if you wanna be featured on https://github.com/sindresorhus/awesome you gotta use lists.

#5 fixes all that + a lot more

**Comment by amrbashir** [comment]
closing in favor of #5

**Pull request closed without merging**
