### PR TITLE
Add Piano Trainer

### PR DESCRIPTION
**Pull request by ZaneH**
This is the link to the project: [Piano Trainer](https://github.com/ZaneH/piano-trainer)

- [x] **I have read the [contributing guidelines](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] Add entries to the bottom of the correct category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Apps

- [x] The app is original and not too simple.
- [x] The README is in English.
- [x] The app makes a reasonable effort to be fast, lightweight and secure.
- [x] If the app closed source, evidence of it being built with Tauri is included.

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
Hey, thanks for being part of the community!
I have only one thing of note: You must update the apps icon to something custom, because of trademark reasons (you know the whole spiel 🤷🏻‍♂️)

**Comment by ZaneH** [comment]
> Hey, thanks for being part of the community! I have only one thing of note: You must update the apps icon to something custom, because of trademark reasons (you know the whole spiel 🤷🏻‍♂️)

Ohp, will do!

**Comment by ZaneH** [comment]
Just updated my branches (and releases) to use this new icon:

image

**Comment by JonasKruckenberg** [comment]
> Just updated my branches (and releases) to use this new icon:
> 
> 
> 
> image
> 
> 

Yeah looks good now, thanks! Just a heads up, I noticed you still have some old icons that probably didn't get replaced by tauricon or whatever. You probably want to remove them 😉

**Review by JonasKruckenberg — APPROVED** [review]

**Pull request merged**
