### PR TITLE
Add Hypetrigger

### PR DESCRIPTION
**Pull request by nathanbabcock**
This is the link to the project: [TITLE](URL)

- [X] **I have read the [contributing guidelines](contributing.md).**
- [X] Use the following format: `[Title](link) - Description.`
- [X] Add entries to the bottom of the correct category.
- [X] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [X] Description does not start with `A` or `An`.
- [X] Description is under 24 words.
- [X] Description has no links or parenthesis.
- [X] Use `backticks` when mentioning package names.
- [X] Double-check spelling and grammar.
- [X] No trailing whitespace is added to the end of any file.
- [X] One suggestion per pull request.
- [X] I understand that my entry will be removed if it violates the guidelines.
- [X] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The template provides enough information about how to get started and what's included.
- [ ] The template is pretty different from the existing templates.

### Apps

- [X] The app is original and not too simple.
- [X] The README is in English.
- [X] The app makes a reasonable effort to be fast, lightweight and secure.
- [X] If the app closed source, evidence of it being built with Tauri is included.

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
You need to provide proof that your App is actually built using Tauri. This can be a video, a debug build (sent privately) or some other means, check out [this previous PR](https://github.com/tauri-apps/awesome-tauri/pull/79) for a great example.

**Comment by nathanbabcock** [comment]
@JonasKruckenberg thank you for the example. Here's a video of the dev build :)

https://user-images.githubusercontent.com/9583103/186958146-5fe373f0-9fb8-4f95-9a4d-a5259efadcbf.mp4

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
Thanks for being part of the community :)

**Comment by nathanbabcock** [comment]
> Thanks for being part of the community :)

Thank you @JonasKruckenberg. This is awesome! 🎉

**Pull request merged**
