### PR TITLE
Add Jane Reader

### PR DESCRIPTION
**Pull request by hut36**
This is the link to the project: [Jane Reader](https://janereader.com)

- [x] **I have read the [contributing guidelines](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] If the project is closed source add the `![closed source]` badge after the `(link)` but before the `-`.
- [x] If the project/article is non-free or paywalled add the `![paid]` badge after the `(link)` but before the `-`.
- [x] Add entries alphabetically to the most appropriate category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The template provides enough information about how to get started and what's included.
- [ ] The template is pretty different from the existing templates.

### Apps

- [x] The app is original and not too simple.
- [x] The README is in English.
- [x] The app makes a reasonable effort to be fast, lightweight and secure.
- [x] If the app closed source, evidence of it being built with Tauri is included.

### CODE REVIEW

**Comment by FabianLars** [comment]
(@simonhyll I requested your review because you created the current categories)

**Comment by simonhyll** [comment]
Thank you for the PR!

I'm not sure what I feel about a Books category 🤔 It feels a bit too niche. When making the categories I had a general rule that I only split things up into new categories if there are multiple apps that can fit into the category. If there isn't at least 2 apps that fit into the category I try putting them into other existing categories.

I would prefer putting this into either something like a Viewers category where all apps can be placed that have something to do with displaying files in general, or into the Utilities section as just generally a utility tool. The app [MBTiles Viewer](https://github.com/Akylas/mbview-rs) could be placed into a Viewers category along with Jane Reader so that it's not an entire category dedicated to a single app.

**Comment by hut36** [comment]
I prefer Utilities. If Utilities is long enough to split it up, let's do it in another commit. What do you think?

**Comment by simonhyll** [comment]
Sorry for not getting back to you sooner @hut36, got a lot of work to do lately 😅 

Sounds good to me! Utilities is definitely due for splitting up, just gotta figure out which ones make up a logical new category. If you put it in there I'll try to find the time Soon™️ to split it up a bit.

**Comment by hut36** [comment]
No worry and thanks for reply, @simonhyll! PR updated.

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
