### PR TITLE
Add tauri-react-template

### PR DESCRIPTION
**Pull request by oSethoum**
- [x] **I have read the [contributing guidelines](contributing.md).**

- [x] Title as described.
- [x] Added to the right category.
- [x] Added to the end of a list.
- [x] The description of your item is a sentence with less than 24 words.
- [x] No links and parentheses in description. 
- [x] The description starts with a capital and ends with a full stop/period.
- [x] The description doesn't start with `A` or `An`.
- [x] No unnecessary words already provided in the context (e.g. `for Tauri`, `a Tauri plugin`).
- [x] Uses proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [x] When mentioning tools, omits versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`.
- [x] When mentioning package names, uses quotes whenever possible.

### Plugins/Tools

- [ ] The plugin/tool is working with **Tauri 1.x and onward**.
- [ ] The project is Open Source.
- [ ] The repo should be at least 30 days old.
- [ ] The documentation is in English.
- [ ] The project is active and maintained (inactive projects for longer 6 months will be removed without further notice).
- [ ] The project accepts contributions.
- [ ] Not a commercial product.

### Starter Templates

- [x] The starter template is working with **Tauri 1.x and onward**.
- [x] The documentation is in English.
- [x] The starter template most provide enough instructions / documentation about how to start up and what's is included.
- [x] The repo should be at least 30 days old.
- [x] Should be differentiable from the existing starter templates.

### Apps

- [x] The project is Open Source.
- [x] The readme is in English.
- [x] The app is original and not too simple.

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
As it is right now, I don't see what advantage this template has over `yarn create tauri-app` abd selecting the `create-vite + react` template 🤔

**Comment by oSethoum** [comment]
@JonasKruckenberg Yes you're right it does not have any advantages, but it's using vite-tauri package to avoid issue https://github.com/tauri-apps/tauri/issues/2794, maybe I will add a UI library and custom title bar, if that's considered as an advantage.

**Comment by JonasKruckenberg** [comment]
> it's using vite-tauri package to avoid issue https://github.com/tauri-apps/tauri/issues/2794, 

That's already an advantage! You just need to change your documentation to advertise it as such! (And actually enable the `vite-plugin-tauri` 😉)

> maybe I will add a UI library and custom title bar, if that's considered as an advantage. 

I don't consider this an advantage, templates should be generic and serve many different users. So custom UI components belong in their own package.

**Comment by oSethoum** [comment]
@JonasKruckenberg  Done.

**Comment by JonasKruckenberg** [comment]
Thanks! Also just noticed, maybe you can link to the official prerequisites document instead. But just a thought 🤔

**Comment by oSethoum** [comment]
@JonasKruckenberg  You mean the official documentation instead of the download page ?
got you, official prerequisites of tauri.  
Done.

**Comment by oSethoum** [comment]
@JonasKruckenberg Anything else before it can be approved ?

**Review by JonasKruckenberg — APPROVED** [review]

**Pull request merged**
