### PR TITLE
Add CubeShuffle app

### PR DESCRIPTION
**Pull request by philipborg**
- [X] **I have read the [contributing guidelines](contributing.md).**

- [X] Title as described.
- [X] Added to the right category.
- [X] Added to the end of a list.
- [X] The description of your item is a sentence with less than 24 words.
- [X] No links and parentheses in description. 
- [X] The description starts with a capital and ends with a full stop/period.
- [X] The description doesn't start with `A` or `An`.
- [X] No unnecessary words already provided in the context (e.g. `for Tauri`, `a Tauri plugin`).
- [X] Uses proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [X] When mentioning tools, omits versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`.
- [X] When mentioning package names, uses quotes whenever possible.

### Plugins/Tools

- [ ] The plugin/tool is working with **Tauri 1.x and onward**.
- [ ] The project is Open Source.
- [ ] The repo should be at least 30 days old.
- [ ] The documentation is in English.
- [ ] The project is active and maintained (inactive projects for longer 6 months will be removed without further notice).
- [ ] The project accepts contributions.
- [ ] Not a commercial product.

### Starter Templates

- [ ] The starter template is working with **Tauri 1.x and onward**.
- [ ] The documentation is in English.
- [ ] The starter template most provide enough instructions / documentation about how to start up and what's is included.
- [ ] The repo should be at least 30 days old.
- [ ] Should be differentiable from the existing starter templates.

### Apps

- [X] The project is Open Source.
- [X] The readme is in English.
- [X] The app is original and not too simple.

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
~~Can you rebase your branch?~~

Nvm, thanks!

**Comment by philipborg** [comment]
> ~Can you rebase your branch?~
> 
> Nvm, thanks!

I goofed up the rebase a bit, give me 5min.

**Comment by JonasKruckenberg** [comment]
> I goofed up the rebase a bit, give me 5min.

The git diff already looks good, but anyway. Let me know where you're ready 👍🏻

Btw: Nice to see a yew app 😁

**Comment by philipborg** [comment]
> > > ~Can you rebase your branch?~
> > 
> > 
> > > 
> > 
> > 
> > > Nvm, thanks!
> > 
> > 
> > I goofed up the rebase a bit, give me 5min.
> 
> The git diff already looks good, but anyway. Let me know where you're ready 👍🏻
> 
> Btw: Nice to see a yew app grin

So, now it's fixed it. I am so used to autosave I forgot to save the file... It's ready.

Yeah, I wanted to try something new with that project and yew was interesting and in hindsight fun. :smile:

**Review by JonasKruckenberg — APPROVED** [review]

**Pull request merged**
