### PR TITLE
Add tauri-notepad to Office & Writing

### PR DESCRIPTION
**Pull request by tywil04**
This is the link to the project: [tauri-notepad](https://github.com/tywil04/tauri-notepad)

- [x] **I have read the [contributing guidelines](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] If the project is closed source add the `![closed source]` badge after the `(link)` but before the `-`.
- [x] If the project/article is non-free or paywalled add the `![paid]` badge after the `(link)` but before the `-`.
- [x] Add entries alphabetically to the most appropriate category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The template provides enough information about how to get started and what's included.
- [ ] The template is pretty different from the existing templates.

### Apps

- [x] The app is original and not too simple.
- [x] The README is in English.
- [x] The app makes a reasonable effort to be fast, lightweight and secure.
- [x] If the app closed source, evidence of it being built with Tauri is included.

### CODE REVIEW

**Comment by FabianLars** [comment]
Thanks for contributing! Unfortunetly your app does not adhere to Tauri's trademark guidelines: <https://tauri.app/about/trademark#general-guidelines> (last part of that section). We'd appreciate if you could rename your project if you want it to be added to the list, thanks :)

**Comment by FabianLars** [comment]
Thanks for adapting so fast! One thing, your last commit wasn't signed anymore but we need _all_ commits to be signed to be able to merge it. Once that's fixed we can merge this, thanks again :)

**Comment by tywil04** [comment]
Yeah i'm working on it, shouldn't be long now.

**Comment by FabianLars** [comment]
take your time :) just wanted to make sure you're aware

**Comment by tywil04** [comment]
Should all be sorted now, thank you for your patience.

**Review by FabianLars — APPROVED** [review]

**Comment by FabianLars** [comment]
thanks again :)

**Pull request merged**
