### PR TITLE
Add Watcher App

### PR DESCRIPTION
**Pull request by windht**
- [x] **I have read the [contributing guidelines](contributing.md).**

- [x] Title as described.
- [x] Added to the right category.
- [x] Added to the end of a list.
- [x] The description of your item is a sentence with less than 24 words.
- [x] No links and parentheses in description. 
- [x] The description starts with a capital and ends with a full stop/period.
- [x] The description doesn't start with `A` or `An`.
- [x] No unnecessary words already provided in the context (e.g. `for Tauri`, `a Tauri plugin`).
- [x] Uses proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [x] When mentioning tools, omits versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`.
- [x] When mentioning package names, uses quotes whenever possible.

### Plugins/Tools

- [ ] The plugin/tool is working with **Tauri 1.x and onward**.
- [ ] The project is Open Source.
- [ ] The repo should be at least 30 days old.
- [ ] The documentation is in English.
- [ ] The project is active and maintained (inactive projects for longer 6 months will be removed without further notice).
- [ ] The project accepts contributions.
- [ ] Not a commercial product.

### Starter Templates

- [ ] The starter template is working with **Tauri 1.x and onward**.
- [ ] The documentation is in English.
- [ ] The starter template most provide enough instructions / documentation about how to start up and what's is included.
- [ ] The repo should be at least 30 days old.
- [ ] Should be differentiable from the existing starter templates.

### Apps

- [x] The project is Open Source.
- [x] The readme is in English.
- [x] The app is original and not too simple.

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
I checked out your app, and it seems it doesn't work as a Tauri app yet. I'm happy to accept your submission when your app is a little more mature. Feel free to reopen this PR then.

**Comment by windht** [comment]
Hi @JonasKruckenberg , do you mind to share me if the app cannot be opened/installed properly on which system? I tested Windows and MacOS on my side it both install and start properly (I don't have a ubuntu by my side though). If so I will take out the ubuntu version for now. Thanks!

**Comment by JonasKruckenberg** [comment]
I tried checking out your app from source and could get to work, but looks like your release versions do work. I'll reopen this PR then.

One thing though: Could you replace the default Tauri icon with a custom one?

**Comment by windht** [comment]
@JonasKruckenberg 
Done replacing the icons and provided a newer release!
Thanks alot for pointing out the issues.

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
Awesome! Thanks for your submission!

**Pull request merged**
