### PR TITLE
add tauri-plugin-fs-pro

### PR DESCRIPTION
**Pull request by ayangweb**
This is the link to the project: [tauri-plugin-fs-pro](https://github.com/ayangweb/tauri-plugin-fs-pro)

- [x] **I have read the [contributing guidelines](https://github.com/tauri-apps/awesome-tauri/blob/dev/.github/contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] If the project is closed source add the `![closed source]` badge after the `(link)` but before the `-`.
- [x] If the project/article is non-free or paywalled add the `![paid]` badge after the `(link)` but before the `-`.
- [x] Add entries alphabetically to the most appropriate category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [x] Works with **Tauri 1.x and onward**.
- [x] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [x] Documentation is in English.
- [x] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The template provides enough information about how to get started and what's included.
- [ ] The template is pretty different from the existing templates.

### Apps

- [ ] The app is original and not too simple.
- [ ] The README is in English.
- [ ] The app makes a reasonable effort to be fast, lightweight and secure.
- [ ] If the app closed source, evidence of it being built with Tauri is included.

### CODE REVIEW

**Comment by FabianLars** [comment]
I'm a bit confused why this plugin exists as-is tbh. fs-extra only existed in v1 because the core fs api was missing things. Your plugin however only supports v2 but all of the listed methods also exist in the official fs plugin (and shell/opener for `open`).

i really don't want to talk bad about your work here of course, i just think that listed community plugins should have value over the official ones.

**Comment by ayangweb** [comment]
1. The `stat` method of `@tauri-apps/plugin-fs` cannot directly retrieve the size of a directory. See: [issue comment](https://github.com/tauri-apps/plugins-workspace/issues/1927#issuecomment-2409000724).  
2. The `metadata` method provided by `tauri-plugin-fs-pro` calculates the `size` of a directory, and in view of the time-consuming issues, additional methods such as `isDir` are provided separately.
3. While `@tauri-apps/plugin-shell` allows paths to be opened in the default application, `tauri-plugin-fs-pro` adds support for opening paths directly in the file explorer.  
4. Due to time constraints, priority is being given to developing the plugin's v2 version. Support for v1 may be added later if needed.

**Comment by FabianLars** [comment]
1. ah my bad, didn't see the use of fs-extra
2. 👍 
3. plugin-opener, which pulled out the opening feature out of plugin-shell into a seperate plugin supports that too (will be released soon https://github.com/tauri-apps/plugins-workspace/pull/2011)
4. 👍 

I think for the dirSize thing we also would have accepted a PR, just as a seperate function instead of adding it to the metadata (so basically your point 2 but the other way around)

I will leave this PR unmerged for a few more days to see if the rest of the team has any opinions

**Comment by ayangweb** [comment]
Well eh, the opener plugin did work for me, and I added the `compress`, `decompress`, and `transfer` methods!

**Comment by ayangweb** [comment]
Regarding the release of the opener plugin, it was really helpful to me! Also, I added `compress`, `decompress` and `transfer` methods to fs-pro.

As for the `size` method, I can try to provide a PR if needed, but since I'm not proficient enough with Rust, I probably can't guarantee that I'll be able to do it.

**Comment by FabianLars** [comment]
> As for the size method, I can try to provide a PR if needed, but since I'm not proficient enough with Rust, I probably can't guarantee that I'll be able to do it.

no worries :)

> Also, I added compress, decompress and transfer methods to fs-pro.

that's reason enough to merge this pr then :D

**Review by FabianLars — APPROVED** [review]

**Comment by ayangweb** [comment]
🌹

**Comment by ayangweb** [comment]
I've roughly written it down for you to read first!

```rs
#[tauri::command]
pub async fn size<R: Runtime>(
    webview: Webview<R>,
    global_scope: GlobalScope<Entry>,
    command_scope: CommandScope<Entry>,
    path: SafeFilePath,
    options: Option<BaseOptions>,
) -> CommandResult<u64> {
    let resolved_path = resolve_path(
        &webview,
        &global_scope,
        &command_scope,
        path,
        options.as_ref().and_then(|o| o.base_dir),
    )?;

    if resolved_path.is_file() {
        Ok(0)
    } else {
        let size = get_dir_size(resolved_path).map_err(|e| {
            format!(
                "failed to get size at path: {} with error: {e}",
                path.display()
            )
        })?;

        Ok(size)
    }
}

fn get_dir_size(path: PathBuf) -> CommandResult<u64> {
    let mut size = 0;

    for entry in std::fs::read_dir(path)? {
        let entry = entry?;
        let metadata = entry.metadata()?;

        if metadata.is_file() {
            size += metadata.len();
        } else if metadata.is_dir() {
            size += get_dir_size(entry.path())?;
        }
    }

    Ok(size)
}
```

**Comment by ayangweb** [comment]
I've roughly written it down for you to read first!

```rs
#[tauri::command]
pub async fn size<R: Runtime>(
    webview: Webview<R>,
    global_scope: GlobalScope<Entry>,
    command_scope: CommandScope<Entry>,
    path: SafeFilePath,
    options: Option<BaseOptions>,
) -> CommandResult<u64> {
    let resolved_path = resolve_path(
        &webview,
        &global_scope,
        &command_scope,
        path,
        options.as_ref().and_then(|o| o.base_dir),
    )?;

    let metadata = resolved_path.metadata()?;

    if metadata.is_file() {
        Ok(metadata.len())
    } else {
        let size = get_dir_size(resolved_path).map_err(|e| {
            format!(
                "failed to get size at path: {} with error: {e}",
                path.display()
            )
        })?;

        Ok(size)
    }
}

fn get_dir_size(path: PathBuf) -> CommandResult<u64> {
    let mut size = 0;

    for entry in std::fs::read_dir(path)? {
        let entry = entry?;
        let metadata = entry.metadata()?;

        if metadata.is_file() {
            size += metadata.len();
        } else if metadata.is_dir() {
            size += get_dir_size(entry.path())?;
        }
    }

    Ok(size)
}
```

**Comment by FabianLars** [comment]
that looks fine at first glance

**Comment by ayangweb** [comment]
I pr a prototype, you help me to optimize it again, thanks!

**Comment by ayangweb** [comment]
https://github.com/tauri-apps/plugins-workspace/pull/2095 thank you for your time.🌹

**Pull request merged**
