### PR TITLE
Add tauri-nextjs-template

### PR DESCRIPTION
**Pull request by kvnxiao**
This is the link to the project: [tauri-nextjs-template](https://github.com/kvnxiao/tauri-nextjs-template)

- [x] **I have read the [contributing guidelines](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] Add entries to the bottom of the correct category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [x] Works with **Tauri 1.x and onward**.
- [x] The repo is at least 30 days old.
- [x] Documentation is in English.
- [x] The template provides enough information about how to get started and what's included.
- [x] The template is pretty different from the existing templates.

### Apps

- [ ] The app is original and not too simple.
- [ ] The README is in English.
- [ ] The app makes a reasonable effort to be fast, lightweight and secure.
- [ ] If the app closed source, evidence of it being built with Tauri is included.

### CODE REVIEW

**Comment by kvnxiao** [comment]
Apologies for the ping but @JonasKruckenberg could I get a quick review on this?

**Comment by amrbashir** [comment]
Please be patient, Jonas is currently away on holiday, he will review whenever he is back and available.

**Comment by JonasKruckenberg** [comment]
Interesting, I actually didn't get any notification for this whatsoever 😟
I will review this tomorrow! Cool to see a NextJS integration we talked about a lot on discord as an actual template.

**Review by JonasKruckenberg — CHANGES_REQUESTED** [review]
Okay @kvnxiao I will use this PR to note a few things:

1. Leave the bundle identifier as the default. We have checks in the CLI to help people catch this common problem, bc users really must change this ID to something custom.
```diff
-"identifier": "com.github.your-name-here",
+"identifier": "com.tauri.dev",
```

2. Consider changing the `yarn dev` and `yarn build` commands to directly call the tauri CLI instead of only nextjs

**Comment by kvnxiao** [comment]
@JonasKruckenberg Addressed 1. via https://github.com/kvnxiao/tauri-nextjs-template/commit/25929bd94af0130ce6395ab8dea7403b2f7d71f6

As for 2., addressed via https://github.com/kvnxiao/tauri-nextjs-template/commit/3f936cbea2fcc4651415725855ad7ef43a688af4

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
Thanks for being part of the community!

**Pull request merged**
