### PR TITLE
Add tauri-app [Lanaya]

### PR DESCRIPTION
**Pull request by ChurchTao**
This is the link to the project: [Lanaya](https://github.com/ChurchTao/Lanaya)

- [x] **I have read the [contributing guidelines](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] Add entries to the bottom of the correct category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Apps

- [x] The app is original and not too simple.
- [x] The README is in English.
- [x] The app makes a reasonable effort to be fast, lightweight and secure.
- [x] If the app closed source, evidence of it being built with Tauri is included.

### Additional Context

### CODE REVIEW

**Comment by ChurchTao** [comment]
@JonasKruckenberg 
About [https://github.com/tauri-apps/awesome-tauri/pull/113](url)
I resubmitted after learning the signed across 😄 also, I found it really necessary to sign the commit! 
Learned a lot~

**Comment by JonasKruckenberg** [comment]
Great! Now if you could update that CSP once again I feel good with merging this 👍🏻 
If you're unsure, generally you start out with `"default-src 'none'"`, build the app using `tauri build --debug`, see what errors the dev tools console gives you and repeat until there are no more issues. This way you end up with the tightest possible CSP

**Comment by ChurchTao** [comment]
> Great! Now if you could update that CSP once again I feel good with merging this 👍🏻 If you're unsure, generally you start out with `"default-src 'none'"`, build the app using `tauri build --debug`, see what errors the dev tools console gives you and repeat until there are no more issues. This way you end up with the tightest possible CSP

I fell asleep too late yesterday, and I tried your steps today, and I have modified the CSP.

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
> > Great! Now if you could update that CSP once again I feel good with merging this 👍🏻 If you're unsure, generally you start out with `"default-src 'none'"`, build the app using `tauri build --debug`, see what errors the dev tools console gives you and repeat until there are no more issues. This way you end up with the tightest possible CSP
> 
> I fell asleep too late yesterday, and I tried your steps today, and I have modified the CSP.

No worries, looks good now!

**Pull request merged**
