### PR TITLE
add leptos template

### PR DESCRIPTION
**Pull request by kandrelczyk**
This is the link to the project: [tauri-leptos-tempalte](https://gitlab.com/cristofa/tauri-leptos-template)

- [x] **I have read the [contributing guidelines](https://github.com/tauri-apps/awesome-tauri/blob/dev/.github/contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] If the project is closed source add the `![closed source]` badge after the `(link)` but before the `-`.
- [x] If the project/article is non-free or paywalled add the `![paid]` badge after the `(link)` but before the `-`.
- [x] Add entries alphabetically to the most appropriate category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [x] Documentation is in English.
- [x] The template provides enough information about how to get started and what's included.
- [x] The template is pretty different from the existing templates.

### Apps

- [ ] The app is original and not too simple.
- [ ] The README is in English.
- [ ] The app makes a reasonable effort to be fast, lightweight and secure.
- [ ] If the app closed source, evidence of it being built with Tauri is included.

### Additional Context

I've noticed Leptos template is missing and the one provided with create-tauri-app is very simple. I created a template showing how to properly use tauri commands with Leptos resources. I also included event example and tailwind css integration. All those things are not covered in any documentation I've seen. It's using Tauri 2.0  and it's not 30 days old though... Can it still be included?

### CODE REVIEW

**Comment by FabianLars** [comment]
> It's using Tauri 2.0 and it's not 30 days old though

Maybe add a note about it being v2 alpha/beta in the readme? Also, i'd wait with merging this until it was changed to v2 beta which we're releasing right now.

I don't really care about the 30 days rule so don't worry about that.

p.s. thanks for contributing :)

**Comment by kandrelczyk** [comment]
Ok, no problem. I will update the readme and push another commit after I tested it with 2.0bet. Good to hear it's moving to beta!

**Comment by kandrelczyk** [comment]
Hi @FabianLars, I updated the template to v2 beta and add info to the readme.

**Review by FabianLars — APPROVED** [review]
thank you!

**Pull request merged**
