### PR TITLE
Add MDX Editor

### PR DESCRIPTION
**Pull request by maqi1520**
This is the link to the project: [MDX Editor](https://github.com/maqi1520/mdx-editor/tree/tauri-app)

- [X] **I have read the [contributing guidelines](contributing.md).**
- [X] Use the following format: `[Title](link) - Description.`
- [X] If the project is closed source add the `![closed source]` badge after the `(link)` but before the `-`.
- [X] If the project/article is non-free or paywalled add the `![paid]` badge after the `(link)` but before the `-`.
- [X] Add entries alphabetically to the most appropriate category.
- [X] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [X] Description does not start with `A` or `An`.
- [X] Description is under 24 words.
- [X] Description has no links or parenthesis.
- [X] Use `backticks` when mentioning package names.
- [X] Double-check spelling and grammar.
- [X] No trailing whitespace is added to the end of any file.
- [X] One suggestion per pull request.
- [X] I understand that my entry will be removed if it violates the guidelines.
- [X] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The template provides enough information about how to get started and what's included.
- [ ] The template is pretty different from the existing templates.

### Apps

- [x] The app is original and not too simple.
- [x] The README is in English.
- [x] The app makes a reasonable effort to be fast, lightweight and secure.
- [x] If the app closed source, evidence of it being built with Tauri is included.

### CODE REVIEW

**Review by FabianLars — DISMISSED** [review]
Awesome, thanks!

**Comment by FabianLars** [comment]
Whoops, jumped the gun there again. Your commit is not signed yet so we can't merge this yet (github disables the merge button). Please follow [this guide](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) from the checklist and sign _all_ commits in the PR (meaning a force push will be needed to overwrite the existing commit)

**Comment by maqi1520** [comment]
Okay, I'm done

**Comment by FabianLars** [comment]
Thanks! It still shows as unverified though (so the commit is indeed signed now but github can't verify it).
Sounds like you didn't upload your key to github yet:
grafik

**Comment by maqi1520** [comment]
Thanks, The commit has been verified

**Review by FabianLars — APPROVED** [review]
Thanks :)

**Pull request merged**
