### PR TITLE
Add open-source Tauri app to the list 

### PR DESCRIPTION
**Pull request by likui628**
This is the link to the project: [chatbox](https://github.com/Bin-Huang/chatbox)

- [x] **I have read the [contributing guidelines](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] Add entries to the bottom of the correct category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The template provides enough information about how to get started and what's included.
- [ ] The template is pretty different from the existing templates.

### Apps

- [ ] The app is original and not too simple.
- [ ] The README is in English.
- [ ] The app makes a reasonable effort to be fast, lightweight and secure.
- [ ] If the app closed source, evidence of it being built with Tauri is included.

### CODE REVIEW

**Review by FabianLars — APPROVED** [review]
This may be the last chatgpt app i'll merge 😂

**Comment by orangelckc** [comment]
> This may be the last chatgpt app i'll merge 😂

Are you serious? 😭 
I just want to introduce our new teamwork chatgpt launcher.  We have just climb on today's github trending. 
We're still working hard on internationalization process. If you have a moment, please take a look at our project. It's a really cool helper for PC users.
https://github.com/Synaptrix/ChatGPT-Desktop

**Comment by FabianLars** [comment]
idk, you'd be the third app which i guess is still fine. I saw like 10 other chatgpt tauri apps out there so at some point we really have to stop adding them to this list :D

About your app in particular, internationalization would be nice but i don't think we have a hard requirement on the app's language, only the readme.
Also one thing i'm honestly not a fan of is your fs scope in the allowlist. From my experience `["**"]` is rarely actually needed so unless there's a really good reason i suggest changing this before opening a PR :)

**Comment by orangelckc** [comment]
> idk, you'd be the third app which i guess is still fine. I saw like 10 other chatgpt tauri apps out there so at some point we really have to stop adding them to this list :D
> 
> About your app in particular, internationalization would be nice but i don't think we have a hard requirement on the app's language, only the readme. Also one thing i'm honestly not a fan of is your fs scope in the allowlist. From my experience `["**"]` is rarely actually needed so unless there's a really good reason i suggest changing this before opening a PR :)

Thank you for the suggestion. We will publish a new version to address this risk. Our team is new to the Tauri ecosystem and is still learning about this amazing solution for all platforms. If you have any ideas that can assist us, please feel free to share them with us. 😄 

Later today, we will be adding the English version of our README. Afterward, I will submit a pull request regarding our application. Are there any additional requirements that I need to adhere to?

**Comment by FabianLars** [comment]
When you create a PR it will automatically have a template with a list of the current requirements. If you want to know it upfront, take a look at this https://github.com/tauri-apps/awesome-tauri/blob/dev/.github/contributing.md

**Comment by orangelckc** [comment]
> When you create a PR it will automatically have a template with a list of the current requirements. If you want to know it upfront, take a look at this https://github.com/tauri-apps/awesome-tauri/blob/dev/.github/contributing.md

I have just submitted a PR of our project #149. Please take a look. Thanks for your time.

**Pull request merged**
