### PR TITLE
add semanmeter

### PR DESCRIPTION
**Pull request by wkl007**
This is the link to the project: [Semanmeter](https://yibiao.fun/)

- [x] **I have read the [[contributing guidelines](https://github.com/tauri-apps/awesome-tauri/compare/contributing.md)](contributing.md).**
- [x] Use the following format: `[Title](link) - Description.`
- [x] Add entries to the bottom of the correct category.
- [x] No unnecessary words like `for Tauri`, `a Tauri plugin` and `Super-Fast`.
- [x] Description does not start with `A` or `An`.
- [x] Description is under 24 words.
- [x] Description has no links or parenthesis.
- [x] Use `backticks` when mentioning package names.
- [x] Double-check spelling and grammar.
- [x] No trailing whitespace is added to the end of any file.
- [x] One suggestion per pull request.
- [x] I understand that my entry will be removed if it violates the guidelines.
- [x] I have [signed my commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

### Plugins/Integrations

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The project is open source and accepts contributions.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The project is active and maintained.

### Templates

- [ ] Works with **Tauri 1.x and onward**.
- [ ] The repo is at least 30 days old.
- [ ] Documentation is in English.
- [ ] The template provides enough information about how to get started and what's included.
- [ ] The template is pretty different from the existing templates.

### Apps

- [x] The app is original and not too simple.
- [ ] The README is in English.
- [x] The app makes a reasonable effort to be fast, lightweight and secure.
- [x] If the app closed source, evidence of it being built with Tauri is included.

### Additional Context

### CODE REVIEW

**Comment by wkl007** [comment]
https://user-images.githubusercontent.com/23228335/209499273-d423113d-9519-4555-954d-b1d8d4a9bedf.mp4

**Review by JonasKruckenberg — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
Hey! Awesome, thank you for including that screenrecording out of the gate 👍

However, we require all commits to be signed across Tauri's repositories. Follow [this guide](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) to set up commit signing. Once all the commits in this PR are signed we can merge your contribution. Thanks for being part of our community!

**Comment by wkl007** [comment]
@JonasKruckenberg Hello，this project is on our company's gitlab private server, I don't know how to sign my commits, please help me.😘

**Comment by JonasKruckenberg** [comment]
You do not need to sign the commits of your main apps repo (why would we care about that, it's your companies repo after all 😉)
What we do care about is the commit that adds your app to **this** repo (i.e. the one that this PR is about)

If you have set up the necessary keys for commit signing, you can either close this PR and create a new one where the commit is signed *or* you use this command which will sign thar previous commit:

```
git rebase --exec 'git commit --amend --no-edit -n -S' -i e18fefe4e7614e5e9350e6168785f5402b0456db

# don't forget you need to force push now
git push --force
```

**Comment by wkl007** [comment]
@JonasKruckenberg I get it, thank you very much, I love you😘

**Comment by JonasKruckenberg** [comment]
I've updated my previous commit with some more details too 👍

**Comment by wkl007** [comment]
@JonasKruckenberg I have already dealt with it, please check the commit.

image

**Comment by JonasKruckenberg** [comment]
Yup!

**Pull request merged**
